# Is the Lottery truly a random thing? Are there no patterns to predict??

## Step 1 - get some data in.

In [37]:
import pandas as pd

# the data is from a web site purporting to list all draws since 1994 in the order the numbers came out

df = pd.read_csv('/home/chris/Documents/lottery2.csv')

df.columns = ('Draw', 'Day', 'Date', 'Month', 'Year', 'N1', 'N2', 'N3', 'N4', 'N5', 'N6', 'B', 'Jackpot', 'Wins', 'Machine', 'Set')

df = df[['N1','N2','N3','N4','N5','N6','B']] 

df

      N1  N2  N3  N4  N5  N6   B
0      1  38  54  31  28  16   5
1     59  11  21  49  13  37   4
2     47  23  56  38  28  17  31
3     15  18  52  42  43  23  28
4     44  41  49  54  23   7  37
5      6  30  27  50   9  40  22
6     15   6  45   8  58  31  39
7     34  23  43  45  21   5  20
8     53   4  23   9  37  20  39
9     52  37  58   4  40  13  51
10    28  20  27  53  14   8  45
11    21  54  36  53  14  19  33
12    29  35  26  46  21  59  10
13     8  33  45  16  51  36  38
14    49  42  10  48  37  29  32
15    54  41  17  51  10  35  25
16    52   5  47  48  54  40  33
17    58  16  19  29  54  46  12
18    22  52  13  35  10  42  27
19    11  32   2  54  18  40   8
20    40  58   7   8   3   9  36
21    11  26  32  33  31  46  20
22    27  44  58  31  16  32  42
23     3  21   9   8  54  19  31
24    55  25  39  45  20  10  22
25     2  49  40  28   1  48  17
26    25   4  38  39   2   8  29
27    37   7   8  28   5  16  40
28     7  33  12  50  51  47  40
29    55  31   3  11  16  44   8
...   ..  ..  ..  ..  ..  ..  ..
2179  44  15  26  46  12  49  14
2180  31   1  29  40  21  32  27
2181  45  12  25  37  44  13   9
2182  46  15  17  28  16  32  22
2183  41  16  28  25   7  26  19
2184  35  14  48  17  43   5  22
2185  31   9  15  34  48  22  23
2186  33  36   8  20  38  18  46
2187   1  23  26   4   6  49   8
2188  42  17  22  24  47  14  34
2189  43  41  22  25  30  32  29
2190   4  49  41  44  42  17  24
2191  41  19  31  18   9  24  21
2192   2  22  13  46  29  27  36
2193  17  36  11  12  42  26  13
2194  18  33   8  31   5  10  28
2195  45  16  36  19  21  29  43
2196  48  38  15  29  18  35   5
2197  46  42   1  38   7  37  20
2198  31  16  25  43   4  26  21
2199  47   6  16  31  30  20   4
2200  23  38  17   7  32  42  48
2201  21  32   2   5  25  22  46
2202  17  44  36  32   9  42  16
2203  27  29  39   3  44   2   6
2204  13   3  38   5  14   9  30
2205  26  47  49  43  35  38  28
2206  21  11  17  30  29  40  31
2207  16   6  44  31  12  15  37
2208  30   3   5  44  14  22  10

[2209 rows x 7 columns]

## Just calculating the sum of each row

In [38]:
df['Sum'] = df.sum(axis=1)

df[['Sum']]

      Sum
0     173
1     194
2     240
3     221
4     255
5     184
6     202
7     191
8     185
9     255
10    195
11    230
12    226
13    227
14    247
15    233
16    279
17    234
18    201
19    165
20    161
21    199
22    250
23    145
24    216
25    185
26    145
27    141
28    240
29    168
...   ...
2179  206
2180  181
2181  185
2182  176
2183  162
2184  184
2185  182
2186  199
2187  117
2188  200
2189  222
2190  221
2191  163
2192  175
2193  157
2194  133
2195  209
2196  188
2197  191
2198  166
2199  154
2200  207
2201  153
2202  196
2203  150
2204  112
2205  266
2206  179
2207  161
2208  128

[2209 rows x 1 columns]

## multiply each number by each othe number in each row

In [39]:
df['Mul'] = df[['N1']].multiply(df['N2'].multiply(df['N3']).multiply(df['N4']).multiply(df['N5']).multiply(df['N6']).multiply(df['B']), axis='index')
df[['Mul']]

              Mul
0       142490880
1      1284887604
2     33944230208
3     16329418560
4     28435048488
5      1924560000
6      2271952800
7      3177657000
8      1266492240
9     11837679360
10     4038854400
11    18992712816
12    15040716600
13    13261501440
14    33918474240
15    16795957500
16    41809996800
17    15241665024
18     5902696800
19      218972160
20      126282240
21     8613496320
22    45933060096
23      144272016
24    10617750000
25       89564160
26       68764800
27      185651200
28    13288968000
29      316884480
...           ...
2179   6498011520
2180    652458240
2181   2571426000
2182   3699548160
2183   1587913600
2184   1891243200
2185   3455939520
2186   5980677120
2187      5625984
2188   8434065024
2189  26995056000
2190   6059015424
2191   1971717552
2192    741682656
2193   1146809664
2194    206236800
2195  12896573760
2196   2499336000
2197    380294880
2198   1164508800
2199    335692800
2200   6709635072
2201    170016000
2202   5211537408
2203     48370608
2204     28009800
2205  95883838960
2206   4236447600
2207    872087040
2208     60984000

[2209 rows x 1 columns]

## Divide Mul by Sum, subtract Divres from Mul (Diff)

In [57]:
import pandas as pd
import numpy as np

z = []

df['Divres'] = df['Mul']/df['Sum']

df['Diff'] = df['Mul']-df['Divres']

df['Divres'] = np.round(df[['Divres']], 0)

df['Diff'] = np.round(df[['Diff']], 0)

df['Divres'] = df['Divres'].astype(str)

df[['Sum','Mul','Divres', 'Diff']]

for i in df.Diff:
    
    z.append[i]
    #str = z[i]

    print z

TypeError: 'builtin_function_or_method' object has no attribute '__getitem__'